# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 361, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.textEdit = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.textEdit.setGeometry(QtCore.QRect(10, 0, 104, 45))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 0, 104, 45))
        self.textEdit_2.setObjectName("textEdit_2")
        self.EspSpin = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.EspSpin.setGeometry(QtCore.QRect(20, 50, 48, 26))
        self.EspSpin.setObjectName("EspSpin")
        self.EspAdd = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.EspAdd.setGeometry(QtCore.QRect(70, 50, 41, 26))
        self.EspAdd.setObjectName("EspAdd")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 0, 104, 45))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 80, 104, 45))
        self.textEdit_4.setObjectName("textEdit_4")
        self.AmeSpin = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.AmeSpin.setGeometry(QtCore.QRect(140, 50, 48, 26))
        self.AmeSpin.setObjectName("AmeSpin")
        self.AmeAdd = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.AmeAdd.setGeometry(QtCore.QRect(190, 50, 41, 26))
        self.AmeAdd.setObjectName("AmeAdd")
        self.CafAdd = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.CafAdd.setGeometry(QtCore.QRect(310, 50, 41, 26))
        self.CafAdd.setObjectName("CafAdd")
        self.CafSpin = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.CafSpin.setGeometry(QtCore.QRect(260, 50, 48, 26))
        self.CafSpin.setObjectName("CafSpin")
        self.CapSpin = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.CapSpin.setGeometry(QtCore.QRect(20, 130, 48, 26))
        self.CapSpin.setObjectName("CapSpin")
        self.CapAdd = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.CapAdd.setGeometry(QtCore.QRect(70, 130, 41, 26))
        self.CapAdd.setObjectName("CapAdd")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tabWidgetPage2)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 0, 104, 45))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tabWidgetPage2)
        self.textEdit_6.setGeometry(QtCore.QRect(130, 0, 104, 45))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tabWidgetPage2)
        self.textEdit_7.setGeometry(QtCore.QRect(250, 0, 104, 45))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tabWidgetPage2)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 80, 104, 45))
        self.textEdit_8.setObjectName("textEdit_8")
        self.ChoSpin = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.ChoSpin.setGeometry(QtCore.QRect(20, 50, 48, 26))
        self.ChoSpin.setObjectName("ChoSpin")
        self.ChoAdd = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.ChoAdd.setGeometry(QtCore.QRect(70, 50, 41, 26))
        self.ChoAdd.setObjectName("ChoAdd")
        self.GreAdd = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.GreAdd.setGeometry(QtCore.QRect(190, 50, 41, 26))
        self.GreAdd.setObjectName("GreAdd")
        self.LatAdd = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.LatAdd.setGeometry(QtCore.QRect(310, 50, 41, 26))
        self.LatAdd.setObjectName("LatAdd")
        self.SPAdd = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.SPAdd.setGeometry(QtCore.QRect(70, 130, 41, 26))
        self.SPAdd.setObjectName("SPAdd")
        self.GreSpin = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.GreSpin.setGeometry(QtCore.QRect(140, 50, 48, 26))
        self.GreSpin.setObjectName("GreSpin")
        self.LatSpin = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.LatSpin.setGeometry(QtCore.QRect(260, 50, 48, 26))
        self.LatSpin.setObjectName("LatSpin")
        self.SPSpin = QtWidgets.QSpinBox(self.tabWidgetPage2)
        self.SPSpin.setGeometry(QtCore.QRect(20, 130, 48, 26))
        self.SPSpin.setObjectName("SPSpin")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.Cam = QtWidgets.QTextEdit(self.tabWidgetPage3)
        self.Cam.setGeometry(QtCore.QRect(10, 0, 104, 45))
        self.Cam.setObjectName("Cam")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tabWidgetPage3)
        self.textEdit_10.setGeometry(QtCore.QRect(130, 0, 104, 45))
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tabWidgetPage3)
        self.textEdit_11.setGeometry(QtCore.QRect(250, 0, 104, 45))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tabWidgetPage3)
        self.textEdit_12.setGeometry(QtCore.QRect(10, 80, 104, 45))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tabWidgetPage3)
        self.textEdit_13.setGeometry(QtCore.QRect(130, 80, 104, 45))
        self.textEdit_13.setObjectName("textEdit_13")
        self.CamSpin = QtWidgets.QSpinBox(self.tabWidgetPage3)
        self.CamSpin.setGeometry(QtCore.QRect(20, 50, 48, 26))
        self.CamSpin.setObjectName("CamSpin")
        self.CamAdd = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.CamAdd.setGeometry(QtCore.QRect(70, 50, 41, 26))
        self.CamAdd.setObjectName("CamAdd")
        self.EarSpin = QtWidgets.QSpinBox(self.tabWidgetPage3)
        self.EarSpin.setGeometry(QtCore.QRect(140, 50, 48, 26))
        self.EarSpin.setObjectName("EarSpin")
        self.EarAdd = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.EarAdd.setGeometry(QtCore.QRect(190, 50, 41, 26))
        self.EarAdd.setObjectName("EarAdd")
        self.add_amec_11 = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.add_amec_11.setGeometry(QtCore.QRect(310, 50, 41, 26))
        self.add_amec_11.setObjectName("add_amec_11")
        self.add_amec_12 = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.add_amec_12.setGeometry(QtCore.QRect(70, 130, 41, 26))
        self.add_amec_12.setObjectName("add_amec_12")
        self.spin_amec_11 = QtWidgets.QSpinBox(self.tabWidgetPage3)
        self.spin_amec_11.setGeometry(QtCore.QRect(260, 50, 48, 26))
        self.spin_amec_11.setObjectName("spin_amec_11")
        self.spin_amec_12 = QtWidgets.QSpinBox(self.tabWidgetPage3)
        self.spin_amec_12.setGeometry(QtCore.QRect(20, 130, 48, 26))
        self.spin_amec_12.setObjectName("spin_amec_12")
        self.spin_amec_13 = QtWidgets.QSpinBox(self.tabWidgetPage3)
        self.spin_amec_13.setGeometry(QtCore.QRect(140, 130, 48, 26))
        self.spin_amec_13.setObjectName("spin_amec_13")
        self.add_amec_13 = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.add_amec_13.setGeometry(QtCore.QRect(190, 130, 41, 26))
        self.add_amec_13.setObjectName("add_amec_13")
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.spin_amec_14 = QtWidgets.QSpinBox(self.tab)
        self.spin_amec_14.setGeometry(QtCore.QRect(130, 130, 48, 26))
        self.spin_amec_14.setObjectName("spin_amec_14")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_14.setGeometry(QtCore.QRect(0, 80, 104, 45))
        self.textEdit_14.setObjectName("textEdit_14")
        self.add_amec_14 = QtWidgets.QPushButton(self.tab)
        self.add_amec_14.setGeometry(QtCore.QRect(60, 50, 41, 26))
        self.add_amec_14.setObjectName("add_amec_14")
        self.spin_amec_15 = QtWidgets.QSpinBox(self.tab)
        self.spin_amec_15.setGeometry(QtCore.QRect(10, 130, 48, 26))
        self.spin_amec_15.setObjectName("spin_amec_15")
        self.add_amec_15 = QtWidgets.QPushButton(self.tab)
        self.add_amec_15.setGeometry(QtCore.QRect(180, 130, 41, 26))
        self.add_amec_15.setObjectName("add_amec_15")
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_15.setGeometry(QtCore.QRect(240, 0, 104, 45))
        self.textEdit_15.setObjectName("textEdit_15")
        self.spin_amec_16 = QtWidgets.QSpinBox(self.tab)
        self.spin_amec_16.setGeometry(QtCore.QRect(250, 50, 48, 26))
        self.spin_amec_16.setObjectName("spin_amec_16")
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_16.setGeometry(QtCore.QRect(120, 80, 104, 45))
        self.textEdit_16.setObjectName("textEdit_16")
        self.spin_amec_17 = QtWidgets.QSpinBox(self.tab)
        self.spin_amec_17.setGeometry(QtCore.QRect(130, 50, 48, 26))
        self.spin_amec_17.setObjectName("spin_amec_17")
        self.add_amec_16 = QtWidgets.QPushButton(self.tab)
        self.add_amec_16.setGeometry(QtCore.QRect(300, 50, 41, 26))
        self.add_amec_16.setObjectName("add_amec_16")
        self.textEdit_17 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_17.setGeometry(QtCore.QRect(0, 0, 104, 45))
        self.textEdit_17.setObjectName("textEdit_17")
        self.spin_amec_18 = QtWidgets.QSpinBox(self.tab)
        self.spin_amec_18.setGeometry(QtCore.QRect(10, 50, 48, 26))
        self.spin_amec_18.setObjectName("spin_amec_18")
        self.add_amec_17 = QtWidgets.QPushButton(self.tab)
        self.add_amec_17.setGeometry(QtCore.QRect(60, 130, 41, 26))
        self.add_amec_17.setObjectName("add_amec_17")
        self.textEdit_18 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_18.setGeometry(QtCore.QRect(120, 0, 104, 45))
        self.textEdit_18.setObjectName("textEdit_18")
        self.add_amec_18 = QtWidgets.QPushButton(self.tab)
        self.add_amec_18.setGeometry(QtCore.QRect(180, 50, 41, 26))
        self.add_amec_18.setObjectName("add_amec_18")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.add_amec_19 = QtWidgets.QPushButton(self.tab_2)
        self.add_amec_19.setGeometry(QtCore.QRect(60, 50, 41, 26))
        self.add_amec_19.setObjectName("add_amec_19")
        self.textEdit_20 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_20.setGeometry(QtCore.QRect(240, 0, 104, 45))
        self.textEdit_20.setObjectName("textEdit_20")
        self.spin_amec_21 = QtWidgets.QSpinBox(self.tab_2)
        self.spin_amec_21.setGeometry(QtCore.QRect(250, 50, 48, 26))
        self.spin_amec_21.setObjectName("spin_amec_21")
        self.spin_amec_22 = QtWidgets.QSpinBox(self.tab_2)
        self.spin_amec_22.setGeometry(QtCore.QRect(130, 50, 48, 26))
        self.spin_amec_22.setObjectName("spin_amec_22")
        self.add_amec_21 = QtWidgets.QPushButton(self.tab_2)
        self.add_amec_21.setGeometry(QtCore.QRect(300, 50, 41, 26))
        self.add_amec_21.setObjectName("add_amec_21")
        self.textEdit_22 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_22.setGeometry(QtCore.QRect(0, 0, 104, 45))
        self.textEdit_22.setObjectName("textEdit_22")
        self.spin_amec_23 = QtWidgets.QSpinBox(self.tab_2)
        self.spin_amec_23.setGeometry(QtCore.QRect(10, 50, 48, 26))
        self.spin_amec_23.setObjectName("spin_amec_23")
        self.textEdit_23 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_23.setGeometry(QtCore.QRect(120, 0, 104, 45))
        self.textEdit_23.setObjectName("textEdit_23")
        self.add_amec_23 = QtWidgets.QPushButton(self.tab_2)
        self.add_amec_23.setGeometry(QtCore.QRect(180, 50, 41, 26))
        self.add_amec_23.setObjectName("add_amec_23")
        self.tabWidget.addTab(self.tab_2, "")
        self.priceBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.priceBrowser.setGeometry(QtCore.QRect(30, 320, 361, 192))
        self.priceBrowser.setObjectName("priceBrowser")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(200, 510, 89, 25))
        self.ExitButton.setObjectName("ExitButton")
        self.OrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.OrderButton.setGeometry(QtCore.QRect(110, 510, 89, 25))
        self.OrderButton.setObjectName("OrderButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>coff</p></body></html>"))
        self.tabWidgetPage1.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">cfasdfa</p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Espresso</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">4000</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Americano</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">4000</span></p></body></html>"))
        self.EspAdd.setText(_translate("MainWindow", "Add"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cafe Mocha</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">4500</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cappuccino</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.AmeAdd.setText(_translate("MainWindow", "Add"))
        self.CafAdd.setText(_translate("MainWindow", "Add"))
        self.CapAdd.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "coffee"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choco Latte</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Green Latte</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cafe Latte</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">S.P. Latte</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">6000</span></p></body></html>"))
        self.ChoAdd.setText(_translate("MainWindow", "Add"))
        self.GreAdd.setText(_translate("MainWindow", "Add"))
        self.LatAdd.setText(_translate("MainWindow", "Add"))
        self.SPAdd.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "latte"))
        self.Cam.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Camomile</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Earl Grey</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5500</span></p></body></html>"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lemon Tea</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Black Tea</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">4500</span></p></body></html>"))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Peppermint</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.CamAdd.setText(_translate("MainWindow", "Add"))
        self.EarAdd.setText(_translate("MainWindow", "Add"))
        self.add_amec_11.setText(_translate("MainWindow", "Add"))
        self.add_amec_12.setText(_translate("MainWindow", "Add"))
        self.add_amec_13.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "tea"))
        self.textEdit_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orange</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5500</span></p></body></html>"))
        self.add_amec_14.setText(_translate("MainWindow", "Add"))
        self.add_amec_15.setText(_translate("MainWindow", "Add"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tomato</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5000</span></p></body></html>"))
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Strawberry</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">6000</span></p></body></html>"))
        self.add_amec_16.setText(_translate("MainWindow", "Add"))
        self.textEdit_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Watermelon</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5500</span></p></body></html>"))
        self.add_amec_17.setText(_translate("MainWindow", "Add"))
        self.textEdit_18.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kiwi</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">6000</span></p></body></html>"))
        self.add_amec_18.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "juice"))
        self.add_amec_19.setText(_translate("MainWindow", "Add"))
        self.textEdit_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lemon</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5500</span></p></body></html>"))
        self.add_amec_21.setText(_translate("MainWindow", "Add"))
        self.textEdit_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Grapefruit</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">5500</span></p></body></html>"))
        self.textEdit_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orange</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#729fcf;\">6000</span></p></body></html>"))
        self.add_amec_23.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ade"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.OrderButton.setText(_translate("MainWindow", "Order"))
        self.menuMenu.setTitle(_translate("MainWindow", "Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
